# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PythonCode\code\workplace\TestBoard\test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 1050)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.COM_fram = QtWidgets.QFrame(self.centralwidget)
        self.COM_fram.setGeometry(QtCore.QRect(10, 10, 511, 61))
        self.COM_fram.setFrameShape(QtWidgets.QFrame.Box)
        self.COM_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.COM_fram.setLineWidth(2)
        self.COM_fram.setObjectName("COM_fram")
        self.comboBox_com = QtWidgets.QComboBox(self.COM_fram)
        self.comboBox_com.setGeometry(QtCore.QRect(10, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.comboBox_com.setFont(font)
        self.comboBox_com.setObjectName("comboBox_com")
        self.pushButton_link_com = QtWidgets.QPushButton(self.COM_fram)
        self.pushButton_link_com.setGeometry(QtCore.QRect(190, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_link_com.setFont(font)
        self.pushButton_link_com.setObjectName("pushButton_link_com")
        self.pushButton_sweep_com = QtWidgets.QPushButton(self.COM_fram)
        self.pushButton_sweep_com.setGeometry(QtCore.QRect(350, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_sweep_com.setFont(font)
        self.pushButton_sweep_com.setObjectName("pushButton_sweep_com")
        self.DDM_fram = QtWidgets.QFrame(self.centralwidget)
        self.DDM_fram.setGeometry(QtCore.QRect(10, 100, 511, 911))
        self.DDM_fram.setFrameShape(QtWidgets.QFrame.Box)
        self.DDM_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DDM_fram.setLineWidth(2)
        self.DDM_fram.setObjectName("DDM_fram")
        self.lineEdit_Temp = QtWidgets.QLineEdit(self.DDM_fram)
        self.lineEdit_Temp.setGeometry(QtCore.QRect(100, 40, 71, 31))
        self.lineEdit_Temp.setObjectName("lineEdit_Temp")
        self.lineEdit_VCC = QtWidgets.QLineEdit(self.DDM_fram)
        self.lineEdit_VCC.setGeometry(QtCore.QRect(330, 40, 71, 31))
        self.lineEdit_VCC.setObjectName("lineEdit_VCC")
        self.label_temp = QtWidgets.QLabel(self.DDM_fram)
        self.label_temp.setGeometry(QtCore.QRect(40, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp.setFont(font)
        self.label_temp.setObjectName("label_temp")
        self.label_VCC = QtWidgets.QLabel(self.DDM_fram)
        self.label_VCC.setGeometry(QtCore.QRect(270, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_VCC.setFont(font)
        self.label_VCC.setObjectName("label_VCC")
        self.label_temp_3 = QtWidgets.QLabel(self.DDM_fram)
        self.label_temp_3.setGeometry(QtCore.QRect(180, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_3.setFont(font)
        self.label_temp_3.setObjectName("label_temp_3")
        self.label_temp_4 = QtWidgets.QLabel(self.DDM_fram)
        self.label_temp_4.setGeometry(QtCore.QRect(420, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_4.setFont(font)
        self.label_temp_4.setObjectName("label_temp_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.DDM_fram)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 100, 450, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_A = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_A.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_A.setObjectName("gridLayout_A")
        self.label_temp_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_10.setFont(font)
        self.label_temp_10.setObjectName("label_temp_10")
        self.gridLayout_A.addWidget(self.label_temp_10, 3, 2, 1, 1)
        self.lineEdit_A_42 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_42.setObjectName("lineEdit_A_42")
        self.gridLayout_A.addWidget(self.lineEdit_A_42, 5, 4, 1, 1)
        self.label_temp_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_24.setFont(font)
        self.label_temp_24.setObjectName("label_temp_24")
        self.gridLayout_A.addWidget(self.label_temp_24, 1, 1, 1, 2)
        self.label_temp_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_15.setFont(font)
        self.label_temp_15.setObjectName("label_temp_15")
        self.gridLayout_A.addWidget(self.label_temp_15, 4, 5, 1, 1)
        self.lineEdit_A_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_11.setObjectName("lineEdit_A_11")
        self.gridLayout_A.addWidget(self.lineEdit_A_11, 2, 1, 1, 1)
        self.label_temp_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_22.setFont(font)
        self.label_temp_22.setObjectName("label_temp_22")
        self.gridLayout_A.addWidget(self.label_temp_22, 1, 7, 1, 2)
        self.label_temp_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_17.setFont(font)
        self.label_temp_17.setObjectName("label_temp_17")
        self.gridLayout_A.addWidget(self.label_temp_17, 5, 5, 1, 1)
        self.lineEdit_A_22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_22.setObjectName("lineEdit_A_22")
        self.gridLayout_A.addWidget(self.lineEdit_A_22, 3, 4, 1, 1)
        self.label_temp_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_11.setFont(font)
        self.label_temp_11.setObjectName("label_temp_11")
        self.gridLayout_A.addWidget(self.label_temp_11, 4, 2, 1, 1)
        self.label_temp_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_9.setFont(font)
        self.label_temp_9.setObjectName("label_temp_9")
        self.gridLayout_A.addWidget(self.label_temp_9, 2, 0, 1, 1)
        self.lineEdit_A_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_13.setObjectName("lineEdit_A_13")
        self.gridLayout_A.addWidget(self.lineEdit_A_13, 2, 7, 1, 1)
        self.lineEdit_A_31 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_31.setObjectName("lineEdit_A_31")
        self.gridLayout_A.addWidget(self.lineEdit_A_31, 4, 1, 1, 1)
        self.label_temp_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_23.setFont(font)
        self.label_temp_23.setObjectName("label_temp_23")
        self.gridLayout_A.addWidget(self.label_temp_23, 1, 4, 1, 2)
        self.label_temp_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_8.setFont(font)
        self.label_temp_8.setObjectName("label_temp_8")
        self.gridLayout_A.addWidget(self.label_temp_8, 4, 0, 1, 1)
        self.lineEdit_A_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_23.setObjectName("lineEdit_A_23")
        self.gridLayout_A.addWidget(self.lineEdit_A_23, 3, 7, 1, 1)
        self.label_temp_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_16.setFont(font)
        self.label_temp_16.setObjectName("label_temp_16")
        self.gridLayout_A.addWidget(self.label_temp_16, 2, 5, 1, 1)
        self.lineEdit_A_41 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_41.setObjectName("lineEdit_A_41")
        self.gridLayout_A.addWidget(self.lineEdit_A_41, 5, 1, 1, 1)
        self.lineEdit_A_21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_21.setObjectName("lineEdit_A_21")
        self.gridLayout_A.addWidget(self.lineEdit_A_21, 3, 1, 1, 1)
        self.lineEdit_A_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_12.setObjectName("lineEdit_A_12")
        self.gridLayout_A.addWidget(self.lineEdit_A_12, 2, 4, 1, 1)
        self.label_temp_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_20.setFont(font)
        self.label_temp_20.setObjectName("label_temp_20")
        self.gridLayout_A.addWidget(self.label_temp_20, 4, 8, 1, 1)
        self.label_temp_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_18.setFont(font)
        self.label_temp_18.setObjectName("label_temp_18")
        self.gridLayout_A.addWidget(self.label_temp_18, 3, 8, 1, 1)
        self.label_temp_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_14.setFont(font)
        self.label_temp_14.setObjectName("label_temp_14")
        self.gridLayout_A.addWidget(self.label_temp_14, 3, 5, 1, 1)
        self.lineEdit_A_33 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_33.setObjectName("lineEdit_A_33")
        self.gridLayout_A.addWidget(self.lineEdit_A_33, 4, 7, 1, 1)
        self.label_temp_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_12.setFont(font)
        self.label_temp_12.setObjectName("label_temp_12")
        self.gridLayout_A.addWidget(self.label_temp_12, 5, 2, 1, 1)
        self.label_temp_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_19.setFont(font)
        self.label_temp_19.setObjectName("label_temp_19")
        self.gridLayout_A.addWidget(self.label_temp_19, 5, 8, 1, 1)
        self.label_temp_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_13.setFont(font)
        self.label_temp_13.setObjectName("label_temp_13")
        self.gridLayout_A.addWidget(self.label_temp_13, 2, 2, 1, 1)
        self.label_temp_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_5.setFont(font)
        self.label_temp_5.setObjectName("label_temp_5")
        self.gridLayout_A.addWidget(self.label_temp_5, 3, 0, 1, 1)
        self.lineEdit_A_43 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_43.setObjectName("lineEdit_A_43")
        self.gridLayout_A.addWidget(self.lineEdit_A_43, 5, 7, 1, 1)
        self.label_temp_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_6.setFont(font)
        self.label_temp_6.setObjectName("label_temp_6")
        self.gridLayout_A.addWidget(self.label_temp_6, 5, 0, 1, 1)
        self.label_temp_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_21.setFont(font)
        self.label_temp_21.setObjectName("label_temp_21")
        self.gridLayout_A.addWidget(self.label_temp_21, 2, 8, 1, 1)
        self.lineEdit_A_32 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_A_32.setObjectName("lineEdit_A_32")
        self.gridLayout_A.addWidget(self.lineEdit_A_32, 4, 4, 1, 1)
        self.label_temp_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_25.setFont(font)
        self.label_temp_25.setObjectName("label_temp_25")
        self.gridLayout_A.addWidget(self.label_temp_25, 1, 3, 5, 1)
        self.label_temp_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_26.setFont(font)
        self.label_temp_26.setObjectName("label_temp_26")
        self.gridLayout_A.addWidget(self.label_temp_26, 1, 6, 5, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.DDM_fram)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 280, 461, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_B = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_B.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_B.setObjectName("gridLayout_B")
        self.label_temp_47 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_47.setFont(font)
        self.label_temp_47.setObjectName("label_temp_47")
        self.gridLayout_B.addWidget(self.label_temp_47, 1, 1, 1, 1)
        self.label_temp_33 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_temp_33.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_33.setFont(font)
        self.label_temp_33.setObjectName("label_temp_33")
        self.gridLayout_B.addWidget(self.label_temp_33, 2, 0, 1, 1)
        self.lineEdit_B_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_19.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_19.setObjectName("lineEdit_B_19")
        self.gridLayout_B.addWidget(self.lineEdit_B_19, 2, 9, 1, 1)
        self.label_temp_48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_48.setFont(font)
        self.label_temp_48.setObjectName("label_temp_48")
        self.gridLayout_B.addWidget(self.label_temp_48, 1, 2, 1, 1)
        self.label_temp_49 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_49.setFont(font)
        self.label_temp_49.setObjectName("label_temp_49")
        self.gridLayout_B.addWidget(self.label_temp_49, 1, 3, 1, 1)
        self.label_temp_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_50.setFont(font)
        self.label_temp_50.setObjectName("label_temp_50")
        self.gridLayout_B.addWidget(self.label_temp_50, 1, 4, 1, 1)
        self.label_temp_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_51.setFont(font)
        self.label_temp_51.setObjectName("label_temp_51")
        self.gridLayout_B.addWidget(self.label_temp_51, 1, 5, 1, 1)
        self.label_temp_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_53.setFont(font)
        self.label_temp_53.setObjectName("label_temp_53")
        self.gridLayout_B.addWidget(self.label_temp_53, 1, 6, 1, 1)
        self.label_temp_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_52.setFont(font)
        self.label_temp_52.setObjectName("label_temp_52")
        self.gridLayout_B.addWidget(self.label_temp_52, 1, 7, 1, 1)
        self.label_temp_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_54.setFont(font)
        self.label_temp_54.setObjectName("label_temp_54")
        self.gridLayout_B.addWidget(self.label_temp_54, 1, 8, 1, 1)
        self.label_temp_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_55.setFont(font)
        self.label_temp_55.setObjectName("label_temp_55")
        self.gridLayout_B.addWidget(self.label_temp_55, 1, 9, 1, 1)
        self.lineEdit_B_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_11.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_11.setObjectName("lineEdit_B_11")
        self.gridLayout_B.addWidget(self.lineEdit_B_11, 2, 1, 1, 1)
        self.lineEdit_B_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_21.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_21.setObjectName("lineEdit_B_21")
        self.gridLayout_B.addWidget(self.lineEdit_B_21, 3, 1, 1, 1)
        self.lineEdit_B_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_31.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_31.setObjectName("lineEdit_B_31")
        self.gridLayout_B.addWidget(self.lineEdit_B_31, 4, 1, 1, 1)
        self.lineEdit_B_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_41.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_41.setObjectName("lineEdit_B_41")
        self.gridLayout_B.addWidget(self.lineEdit_B_41, 5, 1, 1, 1)
        self.lineEdit_B_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_12.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_12.setObjectName("lineEdit_B_12")
        self.gridLayout_B.addWidget(self.lineEdit_B_12, 2, 2, 1, 1)
        self.lineEdit_B_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_22.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_22.setObjectName("lineEdit_B_22")
        self.gridLayout_B.addWidget(self.lineEdit_B_22, 3, 2, 1, 1)
        self.lineEdit_B_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_32.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_32.setObjectName("lineEdit_B_32")
        self.gridLayout_B.addWidget(self.lineEdit_B_32, 4, 2, 1, 1)
        self.lineEdit_B_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_42.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_42.setObjectName("lineEdit_B_42")
        self.gridLayout_B.addWidget(self.lineEdit_B_42, 5, 2, 1, 1)
        self.lineEdit_B_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_13.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_13.setObjectName("lineEdit_B_13")
        self.gridLayout_B.addWidget(self.lineEdit_B_13, 2, 3, 1, 1)
        self.lineEdit_B_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_23.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_23.setObjectName("lineEdit_B_23")
        self.gridLayout_B.addWidget(self.lineEdit_B_23, 3, 3, 1, 1)
        self.lineEdit_B_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_33.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_33.setObjectName("lineEdit_B_33")
        self.gridLayout_B.addWidget(self.lineEdit_B_33, 4, 3, 1, 1)
        self.lineEdit_B_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_43.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_43.setObjectName("lineEdit_B_43")
        self.gridLayout_B.addWidget(self.lineEdit_B_43, 5, 3, 1, 1)
        self.lineEdit_B_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_14.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_14.setObjectName("lineEdit_B_14")
        self.gridLayout_B.addWidget(self.lineEdit_B_14, 2, 4, 1, 1)
        self.lineEdit_B_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_24.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_24.setObjectName("lineEdit_B_24")
        self.gridLayout_B.addWidget(self.lineEdit_B_24, 3, 4, 1, 1)
        self.lineEdit_B_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_34.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_34.setObjectName("lineEdit_B_34")
        self.gridLayout_B.addWidget(self.lineEdit_B_34, 4, 4, 1, 1)
        self.lineEdit_B_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_44.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_44.setObjectName("lineEdit_B_44")
        self.gridLayout_B.addWidget(self.lineEdit_B_44, 5, 4, 1, 1)
        self.lineEdit_B_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_15.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_15.setObjectName("lineEdit_B_15")
        self.gridLayout_B.addWidget(self.lineEdit_B_15, 2, 5, 1, 1)
        self.lineEdit_B_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_25.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_25.setObjectName("lineEdit_B_25")
        self.gridLayout_B.addWidget(self.lineEdit_B_25, 3, 5, 1, 1)
        self.lineEdit_B_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_35.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_35.setObjectName("lineEdit_B_35")
        self.gridLayout_B.addWidget(self.lineEdit_B_35, 4, 5, 1, 1)
        self.lineEdit_B_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_45.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_45.setObjectName("lineEdit_B_45")
        self.gridLayout_B.addWidget(self.lineEdit_B_45, 5, 5, 1, 1)
        self.lineEdit_B_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_16.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_16.setObjectName("lineEdit_B_16")
        self.gridLayout_B.addWidget(self.lineEdit_B_16, 2, 6, 1, 1)
        self.lineEdit_B_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_26.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_26.setObjectName("lineEdit_B_26")
        self.gridLayout_B.addWidget(self.lineEdit_B_26, 3, 6, 1, 1)
        self.lineEdit_B_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_36.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_36.setObjectName("lineEdit_B_36")
        self.gridLayout_B.addWidget(self.lineEdit_B_36, 4, 6, 1, 1)
        self.lineEdit_B_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_46.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_46.setObjectName("lineEdit_B_46")
        self.gridLayout_B.addWidget(self.lineEdit_B_46, 5, 6, 1, 1)
        self.lineEdit_B_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_17.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_17.setObjectName("lineEdit_B_17")
        self.gridLayout_B.addWidget(self.lineEdit_B_17, 2, 7, 1, 1)
        self.lineEdit_B_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_27.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_27.setObjectName("lineEdit_B_27")
        self.gridLayout_B.addWidget(self.lineEdit_B_27, 3, 7, 1, 1)
        self.lineEdit_B_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_37.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_37.setObjectName("lineEdit_B_37")
        self.gridLayout_B.addWidget(self.lineEdit_B_37, 4, 7, 1, 1)
        self.lineEdit_B_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_47.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_47.setObjectName("lineEdit_B_47")
        self.gridLayout_B.addWidget(self.lineEdit_B_47, 5, 7, 1, 1)
        self.lineEdit_B_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_48.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_48.setObjectName("lineEdit_B_48")
        self.gridLayout_B.addWidget(self.lineEdit_B_48, 5, 8, 1, 1)
        self.lineEdit_B_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_28.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_28.setObjectName("lineEdit_B_28")
        self.gridLayout_B.addWidget(self.lineEdit_B_28, 3, 8, 1, 1)
        self.lineEdit_B_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_18.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_18.setObjectName("lineEdit_B_18")
        self.gridLayout_B.addWidget(self.lineEdit_B_18, 2, 8, 1, 1)
        self.lineEdit_B_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_38.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_38.setObjectName("lineEdit_B_38")
        self.gridLayout_B.addWidget(self.lineEdit_B_38, 4, 8, 1, 1)
        self.lineEdit_B_49 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_49.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_49.setObjectName("lineEdit_B_49")
        self.gridLayout_B.addWidget(self.lineEdit_B_49, 5, 9, 1, 1)
        self.lineEdit_B_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_39.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_39.setObjectName("lineEdit_B_39")
        self.gridLayout_B.addWidget(self.lineEdit_B_39, 4, 9, 1, 1)
        self.lineEdit_B_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_B_29.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_B_29.setObjectName("lineEdit_B_29")
        self.gridLayout_B.addWidget(self.lineEdit_B_29, 3, 9, 1, 1)
        self.label_temp_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_temp_37.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_37.setFont(font)
        self.label_temp_37.setObjectName("label_temp_37")
        self.gridLayout_B.addWidget(self.label_temp_37, 3, 0, 1, 1)
        self.label_temp_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_temp_38.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_38.setFont(font)
        self.label_temp_38.setObjectName("label_temp_38")
        self.gridLayout_B.addWidget(self.label_temp_38, 4, 0, 1, 1)
        self.label_temp_40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_temp_40.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_40.setFont(font)
        self.label_temp_40.setObjectName("label_temp_40")
        self.gridLayout_B.addWidget(self.label_temp_40, 5, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.DDM_fram)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 450, 414, 176))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_C = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_C.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_C.setObjectName("gridLayout_C")
        self.lineEdit_C_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_32.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_32.setObjectName("lineEdit_C_32")
        self.gridLayout_C.addWidget(self.lineEdit_C_32, 4, 2, 1, 1)
        self.lineEdit_C_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_25.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_25.setObjectName("lineEdit_C_25")
        self.gridLayout_C.addWidget(self.lineEdit_C_25, 3, 5, 1, 1)
        self.lineEdit_C_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_23.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_23.setObjectName("lineEdit_C_23")
        self.gridLayout_C.addWidget(self.lineEdit_C_23, 3, 3, 1, 1)
        self.lineEdit_C_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_43.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_43.setObjectName("lineEdit_C_43")
        self.gridLayout_C.addWidget(self.lineEdit_C_43, 5, 3, 1, 1)
        self.lineEdit_C_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_34.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_34.setObjectName("lineEdit_C_34")
        self.gridLayout_C.addWidget(self.lineEdit_C_34, 4, 4, 1, 1)
        self.lineEdit_C_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_16.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_16.setObjectName("lineEdit_C_16")
        self.gridLayout_C.addWidget(self.lineEdit_C_16, 2, 6, 1, 1)
        self.label_temp_36 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_36.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_36.setFont(font)
        self.label_temp_36.setObjectName("label_temp_36")
        self.gridLayout_C.addWidget(self.label_temp_36, 5, 0, 1, 1)
        self.lineEdit_C_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_21.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_21.setObjectName("lineEdit_C_21")
        self.gridLayout_C.addWidget(self.lineEdit_C_21, 3, 1, 1, 1)
        self.lineEdit_C_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_44.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_44.setObjectName("lineEdit_C_44")
        self.gridLayout_C.addWidget(self.lineEdit_C_44, 5, 4, 1, 1)
        self.lineEdit_C_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_28.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_28.setObjectName("lineEdit_C_28")
        self.gridLayout_C.addWidget(self.lineEdit_C_28, 3, 8, 1, 1)
        self.lineEdit_C_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_33.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_33.setObjectName("lineEdit_C_33")
        self.gridLayout_C.addWidget(self.lineEdit_C_33, 4, 3, 1, 1)
        self.lineEdit_C_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_36.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_36.setObjectName("lineEdit_C_36")
        self.gridLayout_C.addWidget(self.lineEdit_C_36, 4, 6, 1, 1)
        self.lineEdit_C_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_15.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_15.setObjectName("lineEdit_C_15")
        self.gridLayout_C.addWidget(self.lineEdit_C_15, 2, 5, 1, 1)
        self.lineEdit_C_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_11.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_11.setObjectName("lineEdit_C_11")
        self.gridLayout_C.addWidget(self.lineEdit_C_11, 2, 1, 1, 1)
        self.lineEdit_C_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_38.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_38.setObjectName("lineEdit_C_38")
        self.gridLayout_C.addWidget(self.lineEdit_C_38, 4, 8, 1, 1)
        self.lineEdit_C_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_31.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_31.setObjectName("lineEdit_C_31")
        self.gridLayout_C.addWidget(self.lineEdit_C_31, 4, 1, 1, 1)
        self.label_temp_60 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_60.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_60.setFont(font)
        self.label_temp_60.setObjectName("label_temp_60")
        self.gridLayout_C.addWidget(self.label_temp_60, 1, 5, 1, 1)
        self.lineEdit_C_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_14.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_14.setObjectName("lineEdit_C_14")
        self.gridLayout_C.addWidget(self.lineEdit_C_14, 2, 4, 1, 1)
        self.lineEdit_C_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_26.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_26.setObjectName("lineEdit_C_26")
        self.gridLayout_C.addWidget(self.lineEdit_C_26, 3, 6, 1, 1)
        self.lineEdit_C_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_17.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_17.setObjectName("lineEdit_C_17")
        self.gridLayout_C.addWidget(self.lineEdit_C_17, 2, 7, 1, 1)
        self.lineEdit_C_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_35.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_35.setObjectName("lineEdit_C_35")
        self.gridLayout_C.addWidget(self.lineEdit_C_35, 4, 5, 1, 1)
        self.lineEdit_C_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_46.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_46.setObjectName("lineEdit_C_46")
        self.gridLayout_C.addWidget(self.lineEdit_C_46, 5, 6, 1, 1)
        self.lineEdit_C_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_48.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_48.setObjectName("lineEdit_C_48")
        self.gridLayout_C.addWidget(self.lineEdit_C_48, 5, 8, 1, 1)
        self.lineEdit_C_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_42.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_42.setObjectName("lineEdit_C_42")
        self.gridLayout_C.addWidget(self.lineEdit_C_42, 5, 2, 1, 1)
        self.lineEdit_C_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_27.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_27.setObjectName("lineEdit_C_27")
        self.gridLayout_C.addWidget(self.lineEdit_C_27, 3, 7, 1, 1)
        self.lineEdit_C_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_45.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_45.setObjectName("lineEdit_C_45")
        self.gridLayout_C.addWidget(self.lineEdit_C_45, 5, 5, 1, 1)
        self.lineEdit_C_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_47.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_47.setObjectName("lineEdit_C_47")
        self.gridLayout_C.addWidget(self.lineEdit_C_47, 5, 7, 1, 1)
        self.lineEdit_C_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_22.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_22.setObjectName("lineEdit_C_22")
        self.gridLayout_C.addWidget(self.lineEdit_C_22, 3, 2, 1, 1)
        self.lineEdit_C_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_37.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_37.setObjectName("lineEdit_C_37")
        self.gridLayout_C.addWidget(self.lineEdit_C_37, 4, 7, 1, 1)
        self.label_temp_35 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_35.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_35.setFont(font)
        self.label_temp_35.setObjectName("label_temp_35")
        self.gridLayout_C.addWidget(self.label_temp_35, 3, 0, 1, 1)
        self.lineEdit_C_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_13.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_13.setObjectName("lineEdit_C_13")
        self.gridLayout_C.addWidget(self.lineEdit_C_13, 2, 3, 1, 1)
        self.lineEdit_C_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_41.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_41.setObjectName("lineEdit_C_41")
        self.gridLayout_C.addWidget(self.lineEdit_C_41, 5, 1, 1, 1)
        self.lineEdit_C_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_18.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_18.setObjectName("lineEdit_C_18")
        self.gridLayout_C.addWidget(self.lineEdit_C_18, 2, 8, 1, 1)
        self.lineEdit_C_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_24.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_24.setObjectName("lineEdit_C_24")
        self.gridLayout_C.addWidget(self.lineEdit_C_24, 3, 4, 1, 1)
        self.lineEdit_C_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_C_12.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_C_12.setObjectName("lineEdit_C_12")
        self.gridLayout_C.addWidget(self.lineEdit_C_12, 2, 2, 1, 1)
        self.label_temp_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_34.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_34.setFont(font)
        self.label_temp_34.setObjectName("label_temp_34")
        self.gridLayout_C.addWidget(self.label_temp_34, 2, 0, 1, 1)
        self.label_temp_39 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_39.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_39.setFont(font)
        self.label_temp_39.setObjectName("label_temp_39")
        self.gridLayout_C.addWidget(self.label_temp_39, 4, 0, 1, 1)
        self.label_temp_64 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_64.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_64.setFont(font)
        self.label_temp_64.setObjectName("label_temp_64")
        self.gridLayout_C.addWidget(self.label_temp_64, 1, 2, 1, 1)
        self.label_temp_62 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_62.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_62.setFont(font)
        self.label_temp_62.setObjectName("label_temp_62")
        self.gridLayout_C.addWidget(self.label_temp_62, 1, 4, 1, 1)
        self.label_temp_61 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_61.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_61.setFont(font)
        self.label_temp_61.setObjectName("label_temp_61")
        self.gridLayout_C.addWidget(self.label_temp_61, 1, 3, 1, 1)
        self.label_temp_63 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_63.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_63.setFont(font)
        self.label_temp_63.setObjectName("label_temp_63")
        self.gridLayout_C.addWidget(self.label_temp_63, 1, 6, 1, 1)
        self.label_temp_67 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_67.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_67.setFont(font)
        self.label_temp_67.setObjectName("label_temp_67")
        self.gridLayout_C.addWidget(self.label_temp_67, 1, 7, 1, 1)
        self.label_temp_65 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_65.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_65.setFont(font)
        self.label_temp_65.setObjectName("label_temp_65")
        self.gridLayout_C.addWidget(self.label_temp_65, 1, 8, 1, 1)
        self.label_temp_66 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_temp_66.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_66.setFont(font)
        self.label_temp_66.setObjectName("label_temp_66")
        self.gridLayout_C.addWidget(self.label_temp_66, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.DDM_fram)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 640, 276, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_D = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_D.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_D.setObjectName("gridLayout_D")
        self.lineEdit_D_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_14.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_14.setObjectName("lineEdit_D_14")
        self.gridLayout_D.addWidget(self.lineEdit_D_14, 2, 4, 1, 1)
        self.lineEdit_D_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_22.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_22.setObjectName("lineEdit_D_22")
        self.gridLayout_D.addWidget(self.lineEdit_D_22, 3, 2, 1, 1)
        self.label_temp_43 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_43.setMaximumSize(QtCore.QSize(60, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_43.setFont(font)
        self.label_temp_43.setObjectName("label_temp_43")
        self.gridLayout_D.addWidget(self.label_temp_43, 2, 0, 1, 1)
        self.lineEdit_D_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_12.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_12.setObjectName("lineEdit_D_12")
        self.gridLayout_D.addWidget(self.lineEdit_D_12, 2, 2, 1, 1)
        self.label_temp_71 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_71.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_71.setFont(font)
        self.label_temp_71.setObjectName("label_temp_71")
        self.gridLayout_D.addWidget(self.label_temp_71, 1, 3, 1, 1)
        self.lineEdit_D_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_23.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_23.setObjectName("lineEdit_D_23")
        self.gridLayout_D.addWidget(self.lineEdit_D_23, 3, 3, 1, 1)
        self.lineEdit_D_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_21.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_21.setObjectName("lineEdit_D_21")
        self.gridLayout_D.addWidget(self.lineEdit_D_21, 3, 1, 1, 1)
        self.lineEdit_D_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_33.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_33.setObjectName("lineEdit_D_33")
        self.gridLayout_D.addWidget(self.lineEdit_D_33, 4, 3, 1, 1)
        self.label_temp_42 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_42.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_42.setFont(font)
        self.label_temp_42.setObjectName("label_temp_42")
        self.gridLayout_D.addWidget(self.label_temp_42, 3, 0, 1, 1)
        self.label_temp_69 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_69.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_69.setFont(font)
        self.label_temp_69.setObjectName("label_temp_69")
        self.gridLayout_D.addWidget(self.label_temp_69, 1, 2, 1, 1)
        self.label_temp_75 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_75.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_75.setFont(font)
        self.label_temp_75.setObjectName("label_temp_75")
        self.gridLayout_D.addWidget(self.label_temp_75, 1, 1, 1, 1)
        self.label_temp_70 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_70.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_temp_70.setFont(font)
        self.label_temp_70.setObjectName("label_temp_70")
        self.gridLayout_D.addWidget(self.label_temp_70, 1, 4, 1, 1)
        self.lineEdit_D_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_13.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_13.setObjectName("lineEdit_D_13")
        self.gridLayout_D.addWidget(self.lineEdit_D_13, 2, 3, 1, 1)
        self.lineEdit_D_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_24.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_24.setObjectName("lineEdit_D_24")
        self.gridLayout_D.addWidget(self.lineEdit_D_24, 3, 4, 1, 1)
        self.lineEdit_D_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_D_11.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_D_11.setObjectName("lineEdit_D_11")
        self.gridLayout_D.addWidget(self.lineEdit_D_11, 2, 1, 1, 1)
        self.label_temp_44 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_temp_44.setMaximumSize(QtCore.QSize(1000, 24))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.label_temp_44.setFont(font)
        self.label_temp_44.setObjectName("label_temp_44")
        self.gridLayout_D.addWidget(self.label_temp_44, 4, 0, 1, 3)
        self.lineEdit_green = QtWidgets.QLineEdit(self.DDM_fram)
        self.lineEdit_green.setGeometry(QtCore.QRect(350, 710, 39, 24))
        self.lineEdit_green.setMaximumSize(QtCore.QSize(39, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_green.setPalette(palette)
        self.lineEdit_green.setObjectName("lineEdit_green")
        self.lineEdit_white = QtWidgets.QLineEdit(self.DDM_fram)
        self.lineEdit_white.setGeometry(QtCore.QRect(350, 670, 39, 24))
        self.lineEdit_white.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_white.setObjectName("lineEdit_white")
        self.lineEdit_red = QtWidgets.QLineEdit(self.DDM_fram)
        self.lineEdit_red.setGeometry(QtCore.QRect(350, 750, 39, 24))
        self.lineEdit_red.setMaximumSize(QtCore.QSize(39, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_red.setPalette(palette)
        self.lineEdit_red.setObjectName("lineEdit_red")
        self.label_2 = QtWidgets.QLabel(self.DDM_fram)
        self.label_2.setGeometry(QtCore.QRect(400, 680, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.DDM_fram)
        self.label_3.setGeometry(QtCore.QRect(400, 720, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.DDM_fram)
        self.label_4.setGeometry(QtCore.QRect(400, 760, 72, 15))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.DDM_fram)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 800, 479, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_E = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_E.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_E.setObjectName("gridLayout_E")
        self.lineEdit_E_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_E_13.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_E_13.setObjectName("lineEdit_E_13")
        self.gridLayout_E.addWidget(self.lineEdit_E_13, 1, 5, 1, 1)
        self.label_temp_58 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_58.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_58.setFont(font)
        self.label_temp_58.setObjectName("label_temp_58")
        self.gridLayout_E.addWidget(self.label_temp_58, 1, 6, 1, 1)
        self.label_temp_56 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_56.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_56.setFont(font)
        self.label_temp_56.setObjectName("label_temp_56")
        self.gridLayout_E.addWidget(self.label_temp_56, 1, 9, 1, 1)
        self.label_temp_45 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_45.setMaximumSize(QtCore.QSize(1000, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_45.setFont(font)
        self.label_temp_45.setObjectName("label_temp_45")
        self.gridLayout_E.addWidget(self.label_temp_45, 0, 0, 1, 4)
        self.lineEdit_E_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_E_14.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_E_14.setObjectName("lineEdit_E_14")
        self.gridLayout_E.addWidget(self.lineEdit_E_14, 1, 7, 1, 1)
        self.label_temp_41 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_41.setMaximumSize(QtCore.QSize(39, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_41.setFont(font)
        self.label_temp_41.setObjectName("label_temp_41")
        self.gridLayout_E.addWidget(self.label_temp_41, 1, 0, 1, 1)
        self.label_temp_46 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_46.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_46.setFont(font)
        self.label_temp_46.setObjectName("label_temp_46")
        self.gridLayout_E.addWidget(self.label_temp_46, 1, 2, 1, 1)
        self.lineEdit_E_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_E_15.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_E_15.setObjectName("lineEdit_E_15")
        self.gridLayout_E.addWidget(self.lineEdit_E_15, 1, 10, 1, 1)
        self.lineEdit_E_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_E_11.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_E_11.setObjectName("lineEdit_E_11")
        self.gridLayout_E.addWidget(self.lineEdit_E_11, 1, 1, 1, 1)
        self.label_temp_57 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_temp_57.setMaximumSize(QtCore.QSize(36, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_57.setFont(font)
        self.label_temp_57.setObjectName("label_temp_57")
        self.gridLayout_E.addWidget(self.label_temp_57, 1, 4, 1, 1)
        self.lineEdit_E_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_E_12.setMaximumSize(QtCore.QSize(39, 24))
        self.lineEdit_E_12.setObjectName("lineEdit_E_12")
        self.gridLayout_E.addWidget(self.lineEdit_E_12, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_5.setPalette(palette)
        self.label_5.setObjectName("label_5")
        self.gridLayout_E.addWidget(self.label_5, 1, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.LIGHT_frame = QtWidgets.QFrame(self.centralwidget)
        self.LIGHT_frame.setGeometry(QtCore.QRect(530, 100, 321, 311))
        self.LIGHT_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.LIGHT_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LIGHT_frame.setLineWidth(2)
        self.LIGHT_frame.setObjectName("LIGHT_frame")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.LIGHT_frame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(30, 20, 261, 231))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_F = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_F.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_F.setObjectName("gridLayout_F")
        self.lineEdit_F_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_32.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_32.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_32.setObjectName("lineEdit_F_32")
        self.gridLayout_F.addWidget(self.lineEdit_F_32, 2, 2, 1, 1)
        self.lineEdit_F_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_51.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_51.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_51.setObjectName("lineEdit_F_51")
        self.gridLayout_F.addWidget(self.lineEdit_F_51, 4, 1, 1, 1)
        self.lineEdit_F_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_41.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_41.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_41.setObjectName("lineEdit_F_41")
        self.gridLayout_F.addWidget(self.lineEdit_F_41, 3, 1, 1, 1)
        self.lineEdit_F_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_42.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_42.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_42.setObjectName("lineEdit_F_42")
        self.gridLayout_F.addWidget(self.lineEdit_F_42, 3, 2, 1, 1)
        self.lineEdit_F_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_62.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_62.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_62.setObjectName("lineEdit_F_62")
        self.gridLayout_F.addWidget(self.lineEdit_F_62, 5, 2, 1, 1)
        self.label_temp_7 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_temp_7.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_7.setFont(font)
        self.label_temp_7.setObjectName("label_temp_7")
        self.gridLayout_F.addWidget(self.label_temp_7, 0, 0, 1, 1)
        self.lineEdit_F_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_61.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_61.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_61.setObjectName("lineEdit_F_61")
        self.gridLayout_F.addWidget(self.lineEdit_F_61, 5, 1, 1, 1)
        self.lineEdit_F_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_11.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_11.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_11.setObjectName("lineEdit_F_11")
        self.gridLayout_F.addWidget(self.lineEdit_F_11, 0, 1, 1, 1)
        self.lineEdit_F_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_22.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_22.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_22.setObjectName("lineEdit_F_22")
        self.gridLayout_F.addWidget(self.lineEdit_F_22, 1, 2, 1, 1)
        self.lineEdit_F_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_21.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_21.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_21.setObjectName("lineEdit_F_21")
        self.gridLayout_F.addWidget(self.lineEdit_F_21, 1, 1, 1, 1)
        self.lineEdit_F_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_12.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_12.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_12.setObjectName("lineEdit_F_12")
        self.gridLayout_F.addWidget(self.lineEdit_F_12, 0, 2, 1, 1)
        self.lineEdit_F_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_52.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_52.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_52.setObjectName("lineEdit_F_52")
        self.gridLayout_F.addWidget(self.lineEdit_F_52, 4, 2, 1, 1)
        self.lineEdit_F_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_F_31.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_F_31.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_F_31.setObjectName("lineEdit_F_31")
        self.gridLayout_F.addWidget(self.lineEdit_F_31, 2, 1, 1, 1)
        self.label_temp_27 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_27.setFont(font)
        self.label_temp_27.setObjectName("label_temp_27")
        self.gridLayout_F.addWidget(self.label_temp_27, 1, 0, 1, 1)
        self.label_temp_31 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_31.setFont(font)
        self.label_temp_31.setObjectName("label_temp_31")
        self.gridLayout_F.addWidget(self.label_temp_31, 2, 0, 1, 1)
        self.label_temp_30 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_30.setFont(font)
        self.label_temp_30.setObjectName("label_temp_30")
        self.gridLayout_F.addWidget(self.label_temp_30, 3, 0, 1, 1)
        self.label_temp_29 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_29.setFont(font)
        self.label_temp_29.setObjectName("label_temp_29")
        self.gridLayout_F.addWidget(self.label_temp_29, 4, 0, 1, 1)
        self.label_temp_28 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_28.setFont(font)
        self.label_temp_28.setObjectName("label_temp_28")
        self.gridLayout_F.addWidget(self.label_temp_28, 5, 0, 1, 1)
        self.pushButton_light_read = QtWidgets.QPushButton(self.LIGHT_frame)
        self.pushButton_light_read.setGeometry(QtCore.QRect(50, 260, 100, 31))
        self.pushButton_light_read.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_light_read.setFont(font)
        self.pushButton_light_read.setObjectName("pushButton_light_read")
        self.pushButton_light_write = QtWidgets.QPushButton(self.LIGHT_frame)
        self.pushButton_light_write.setGeometry(QtCore.QRect(180, 260, 100, 31))
        self.pushButton_light_write.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_light_write.setFont(font)
        self.pushButton_light_write.setObjectName("pushButton_light_write")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 80, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 440, 72, 15))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.TEMP_fram = QtWidgets.QFrame(self.centralwidget)
        self.TEMP_fram.setGeometry(QtCore.QRect(530, 470, 321, 141))
        self.TEMP_fram.setFrameShape(QtWidgets.QFrame.Box)
        self.TEMP_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TEMP_fram.setLineWidth(2)
        self.TEMP_fram.setObjectName("TEMP_fram")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.TEMP_fram)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 242, 80))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_TEMP = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_TEMP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_TEMP.setObjectName("gridLayout_TEMP")
        self.label_temp_59 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_temp_59.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_59.setFont(font)
        self.label_temp_59.setObjectName("label_temp_59")
        self.gridLayout_TEMP.addWidget(self.label_temp_59, 1, 2, 1, 1)
        self.lineEdit_DDM_TEMP = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_DDM_TEMP.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DDM_TEMP.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_DDM_TEMP.setObjectName("lineEdit_DDM_TEMP")
        self.gridLayout_TEMP.addWidget(self.lineEdit_DDM_TEMP, 0, 1, 1, 1)
        self.lineEdit_AIM_TEMP = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_AIM_TEMP.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_AIM_TEMP.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lineEdit_AIM_TEMP.setObjectName("lineEdit_AIM_TEMP")
        self.gridLayout_TEMP.addWidget(self.lineEdit_AIM_TEMP, 1, 1, 1, 1)
        self.label_temp_32 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_temp_32.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_32.setFont(font)
        self.label_temp_32.setObjectName("label_temp_32")
        self.gridLayout_TEMP.addWidget(self.label_temp_32, 0, 2, 1, 1)
        self.label_temp_68 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_68.setFont(font)
        self.label_temp_68.setObjectName("label_temp_68")
        self.gridLayout_TEMP.addWidget(self.label_temp_68, 0, 0, 1, 1)
        self.label_temp_73 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_temp_73.setFont(font)
        self.label_temp_73.setObjectName("label_temp_73")
        self.gridLayout_TEMP.addWidget(self.label_temp_73, 1, 0, 1, 1)
        self.pushButton_ddm_write = QtWidgets.QPushButton(self.TEMP_fram)
        self.pushButton_ddm_write.setGeometry(QtCore.QRect(270, 30, 40, 81))
        self.pushButton_ddm_write.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_ddm_write.setFont(font)
        self.pushButton_ddm_write.setObjectName("pushButton_ddm_write")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 640, 121, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.BURN_fram = QtWidgets.QFrame(self.centralwidget)
        self.BURN_fram.setGeometry(QtCore.QRect(530, 670, 321, 161))
        self.BURN_fram.setFrameShape(QtWidgets.QFrame.Box)
        self.BURN_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BURN_fram.setLineWidth(2)
        self.BURN_fram.setObjectName("BURN_fram")
        self.pushButton_close_burn = QtWidgets.QPushButton(self.BURN_fram)
        self.pushButton_close_burn.setGeometry(QtCore.QRect(20, 20, 281, 121))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.pushButton_close_burn.setFont(font)
        self.pushButton_close_burn.setObjectName("pushButton_close_burn")
        self.SN_fram = QtWidgets.QFrame(self.centralwidget)
        self.SN_fram.setGeometry(QtCore.QRect(530, 870, 321, 141))
        self.SN_fram.setFrameShape(QtWidgets.QFrame.Panel)
        self.SN_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SN_fram.setLineWidth(2)
        self.SN_fram.setObjectName("SN_fram")
        self.lineEdit_SN = QtWidgets.QLineEdit(self.SN_fram)
        self.lineEdit_SN.setGeometry(QtCore.QRect(70, 60, 230, 32))
        self.lineEdit_SN.setMinimumSize(QtCore.QSize(230, 32))
        self.lineEdit_SN.setObjectName("lineEdit_SN")
        self.label_temp_72 = QtWidgets.QLabel(self.SN_fram)
        self.label_temp_72.setGeometry(QtCore.QRect(10, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_temp_72.setFont(font)
        self.label_temp_72.setObjectName("label_temp_72")
        self.EXIT_fram = QtWidgets.QFrame(self.centralwidget)
        self.EXIT_fram.setGeometry(QtCore.QRect(540, 10, 311, 61))
        self.EXIT_fram.setFrameShape(QtWidgets.QFrame.Panel)
        self.EXIT_fram.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.EXIT_fram.setLineWidth(2)
        self.EXIT_fram.setObjectName("EXIT_fram")
        self.pushButton_exit = QtWidgets.QPushButton(self.EXIT_fram)
        self.pushButton_exit.setGeometry(QtCore.QRect(10, 10, 281, 41))
        self.pushButton_exit.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_com, self.pushButton_link_com)
        MainWindow.setTabOrder(self.pushButton_link_com, self.pushButton_sweep_com)
        MainWindow.setTabOrder(self.pushButton_sweep_com, self.lineEdit_Temp)
        MainWindow.setTabOrder(self.lineEdit_Temp, self.lineEdit_VCC)
        MainWindow.setTabOrder(self.lineEdit_VCC, self.lineEdit_A_11)
        MainWindow.setTabOrder(self.lineEdit_A_11, self.lineEdit_A_12)
        MainWindow.setTabOrder(self.lineEdit_A_12, self.lineEdit_A_13)
        MainWindow.setTabOrder(self.lineEdit_A_13, self.lineEdit_A_21)
        MainWindow.setTabOrder(self.lineEdit_A_21, self.lineEdit_A_22)
        MainWindow.setTabOrder(self.lineEdit_A_22, self.lineEdit_A_23)
        MainWindow.setTabOrder(self.lineEdit_A_23, self.lineEdit_A_31)
        MainWindow.setTabOrder(self.lineEdit_A_31, self.lineEdit_A_32)
        MainWindow.setTabOrder(self.lineEdit_A_32, self.lineEdit_A_33)
        MainWindow.setTabOrder(self.lineEdit_A_33, self.lineEdit_A_41)
        MainWindow.setTabOrder(self.lineEdit_A_41, self.lineEdit_A_42)
        MainWindow.setTabOrder(self.lineEdit_A_42, self.lineEdit_A_43)
        MainWindow.setTabOrder(self.lineEdit_A_43, self.lineEdit_B_11)
        MainWindow.setTabOrder(self.lineEdit_B_11, self.lineEdit_B_12)
        MainWindow.setTabOrder(self.lineEdit_B_12, self.lineEdit_B_13)
        MainWindow.setTabOrder(self.lineEdit_B_13, self.lineEdit_B_14)
        MainWindow.setTabOrder(self.lineEdit_B_14, self.lineEdit_B_15)
        MainWindow.setTabOrder(self.lineEdit_B_15, self.lineEdit_B_16)
        MainWindow.setTabOrder(self.lineEdit_B_16, self.lineEdit_B_17)
        MainWindow.setTabOrder(self.lineEdit_B_17, self.lineEdit_B_18)
        MainWindow.setTabOrder(self.lineEdit_B_18, self.lineEdit_B_19)
        MainWindow.setTabOrder(self.lineEdit_B_19, self.lineEdit_B_21)
        MainWindow.setTabOrder(self.lineEdit_B_21, self.lineEdit_B_22)
        MainWindow.setTabOrder(self.lineEdit_B_22, self.lineEdit_B_23)
        MainWindow.setTabOrder(self.lineEdit_B_23, self.lineEdit_B_24)
        MainWindow.setTabOrder(self.lineEdit_B_24, self.lineEdit_B_25)
        MainWindow.setTabOrder(self.lineEdit_B_25, self.lineEdit_B_26)
        MainWindow.setTabOrder(self.lineEdit_B_26, self.lineEdit_B_27)
        MainWindow.setTabOrder(self.lineEdit_B_27, self.lineEdit_B_28)
        MainWindow.setTabOrder(self.lineEdit_B_28, self.lineEdit_B_29)
        MainWindow.setTabOrder(self.lineEdit_B_29, self.lineEdit_B_31)
        MainWindow.setTabOrder(self.lineEdit_B_31, self.lineEdit_B_32)
        MainWindow.setTabOrder(self.lineEdit_B_32, self.lineEdit_B_33)
        MainWindow.setTabOrder(self.lineEdit_B_33, self.lineEdit_B_34)
        MainWindow.setTabOrder(self.lineEdit_B_34, self.lineEdit_B_35)
        MainWindow.setTabOrder(self.lineEdit_B_35, self.lineEdit_B_36)
        MainWindow.setTabOrder(self.lineEdit_B_36, self.lineEdit_B_37)
        MainWindow.setTabOrder(self.lineEdit_B_37, self.lineEdit_B_38)
        MainWindow.setTabOrder(self.lineEdit_B_38, self.lineEdit_B_39)
        MainWindow.setTabOrder(self.lineEdit_B_39, self.lineEdit_B_41)
        MainWindow.setTabOrder(self.lineEdit_B_41, self.lineEdit_B_42)
        MainWindow.setTabOrder(self.lineEdit_B_42, self.lineEdit_B_43)
        MainWindow.setTabOrder(self.lineEdit_B_43, self.lineEdit_B_44)
        MainWindow.setTabOrder(self.lineEdit_B_44, self.lineEdit_B_45)
        MainWindow.setTabOrder(self.lineEdit_B_45, self.lineEdit_B_46)
        MainWindow.setTabOrder(self.lineEdit_B_46, self.lineEdit_B_47)
        MainWindow.setTabOrder(self.lineEdit_B_47, self.lineEdit_B_48)
        MainWindow.setTabOrder(self.lineEdit_B_48, self.lineEdit_B_49)
        MainWindow.setTabOrder(self.lineEdit_B_49, self.lineEdit_C_11)
        MainWindow.setTabOrder(self.lineEdit_C_11, self.lineEdit_C_12)
        MainWindow.setTabOrder(self.lineEdit_C_12, self.lineEdit_C_13)
        MainWindow.setTabOrder(self.lineEdit_C_13, self.lineEdit_C_14)
        MainWindow.setTabOrder(self.lineEdit_C_14, self.lineEdit_C_15)
        MainWindow.setTabOrder(self.lineEdit_C_15, self.lineEdit_C_16)
        MainWindow.setTabOrder(self.lineEdit_C_16, self.lineEdit_C_17)
        MainWindow.setTabOrder(self.lineEdit_C_17, self.lineEdit_C_18)
        MainWindow.setTabOrder(self.lineEdit_C_18, self.lineEdit_C_21)
        MainWindow.setTabOrder(self.lineEdit_C_21, self.lineEdit_C_22)
        MainWindow.setTabOrder(self.lineEdit_C_22, self.lineEdit_C_23)
        MainWindow.setTabOrder(self.lineEdit_C_23, self.lineEdit_C_24)
        MainWindow.setTabOrder(self.lineEdit_C_24, self.lineEdit_C_25)
        MainWindow.setTabOrder(self.lineEdit_C_25, self.lineEdit_C_26)
        MainWindow.setTabOrder(self.lineEdit_C_26, self.lineEdit_C_27)
        MainWindow.setTabOrder(self.lineEdit_C_27, self.lineEdit_C_28)
        MainWindow.setTabOrder(self.lineEdit_C_28, self.lineEdit_C_31)
        MainWindow.setTabOrder(self.lineEdit_C_31, self.lineEdit_C_32)
        MainWindow.setTabOrder(self.lineEdit_C_32, self.lineEdit_C_33)
        MainWindow.setTabOrder(self.lineEdit_C_33, self.lineEdit_C_34)
        MainWindow.setTabOrder(self.lineEdit_C_34, self.lineEdit_C_35)
        MainWindow.setTabOrder(self.lineEdit_C_35, self.lineEdit_C_36)
        MainWindow.setTabOrder(self.lineEdit_C_36, self.lineEdit_C_37)
        MainWindow.setTabOrder(self.lineEdit_C_37, self.lineEdit_C_38)
        MainWindow.setTabOrder(self.lineEdit_C_38, self.lineEdit_C_41)
        MainWindow.setTabOrder(self.lineEdit_C_41, self.lineEdit_C_42)
        MainWindow.setTabOrder(self.lineEdit_C_42, self.lineEdit_C_43)
        MainWindow.setTabOrder(self.lineEdit_C_43, self.lineEdit_C_44)
        MainWindow.setTabOrder(self.lineEdit_C_44, self.lineEdit_C_45)
        MainWindow.setTabOrder(self.lineEdit_C_45, self.lineEdit_C_46)
        MainWindow.setTabOrder(self.lineEdit_C_46, self.lineEdit_C_47)
        MainWindow.setTabOrder(self.lineEdit_C_47, self.lineEdit_C_48)
        MainWindow.setTabOrder(self.lineEdit_C_48, self.lineEdit_D_11)
        MainWindow.setTabOrder(self.lineEdit_D_11, self.lineEdit_D_12)
        MainWindow.setTabOrder(self.lineEdit_D_12, self.lineEdit_D_13)
        MainWindow.setTabOrder(self.lineEdit_D_13, self.lineEdit_D_14)
        MainWindow.setTabOrder(self.lineEdit_D_14, self.lineEdit_D_21)
        MainWindow.setTabOrder(self.lineEdit_D_21, self.lineEdit_D_22)
        MainWindow.setTabOrder(self.lineEdit_D_22, self.lineEdit_D_23)
        MainWindow.setTabOrder(self.lineEdit_D_23, self.lineEdit_D_24)
        MainWindow.setTabOrder(self.lineEdit_D_24, self.lineEdit_D_33)
        MainWindow.setTabOrder(self.lineEdit_D_33, self.lineEdit_E_11)
        MainWindow.setTabOrder(self.lineEdit_E_11, self.lineEdit_E_12)
        MainWindow.setTabOrder(self.lineEdit_E_12, self.lineEdit_E_13)
        MainWindow.setTabOrder(self.lineEdit_E_13, self.lineEdit_E_14)
        MainWindow.setTabOrder(self.lineEdit_E_14, self.lineEdit_E_15)
        MainWindow.setTabOrder(self.lineEdit_E_15, self.lineEdit_F_11)
        MainWindow.setTabOrder(self.lineEdit_F_11, self.lineEdit_F_12)
        MainWindow.setTabOrder(self.lineEdit_F_12, self.lineEdit_F_21)
        MainWindow.setTabOrder(self.lineEdit_F_21, self.lineEdit_F_22)
        MainWindow.setTabOrder(self.lineEdit_F_22, self.lineEdit_F_31)
        MainWindow.setTabOrder(self.lineEdit_F_31, self.lineEdit_F_32)
        MainWindow.setTabOrder(self.lineEdit_F_32, self.lineEdit_F_41)
        MainWindow.setTabOrder(self.lineEdit_F_41, self.lineEdit_F_42)
        MainWindow.setTabOrder(self.lineEdit_F_42, self.lineEdit_F_51)
        MainWindow.setTabOrder(self.lineEdit_F_51, self.lineEdit_F_52)
        MainWindow.setTabOrder(self.lineEdit_F_52, self.lineEdit_F_61)
        MainWindow.setTabOrder(self.lineEdit_F_61, self.lineEdit_F_62)
        MainWindow.setTabOrder(self.lineEdit_F_62, self.pushButton_light_read)
        MainWindow.setTabOrder(self.pushButton_light_read, self.pushButton_light_write)
        MainWindow.setTabOrder(self.pushButton_light_write, self.lineEdit_DDM_TEMP)
        MainWindow.setTabOrder(self.lineEdit_DDM_TEMP, self.lineEdit_AIM_TEMP)
        MainWindow.setTabOrder(self.lineEdit_AIM_TEMP, self.pushButton_ddm_write)
        MainWindow.setTabOrder(self.pushButton_ddm_write, self.pushButton_close_burn)
        MainWindow.setTabOrder(self.pushButton_close_burn, self.lineEdit_SN)
        MainWindow.setTabOrder(self.lineEdit_SN, self.lineEdit_white)
        MainWindow.setTabOrder(self.lineEdit_white, self.lineEdit_green)
        MainWindow.setTabOrder(self.lineEdit_green, self.lineEdit_red)
        MainWindow.setTabOrder(self.lineEdit_red, self.pushButton_exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MapleTest"))
        self.pushButton_link_com.setText(_translate("MainWindow", "链接设备"))
        self.pushButton_sweep_com.setText(_translate("MainWindow", "扫描设备"))
        self.label_temp.setText(_translate("MainWindow", "TEMP:"))
        self.label_VCC.setText(_translate("MainWindow", "VCC:"))
        self.label_temp_3.setText(_translate("MainWindow", "℃"))
        self.label_temp_4.setText(_translate("MainWindow", "V"))
        self.label_temp_10.setText(_translate("MainWindow", "ma"))
        self.label_temp_24.setText(_translate("MainWindow", "Bisa"))
        self.label_temp_15.setText(_translate("MainWindow", "dBm"))
        self.label_temp_22.setText(_translate("MainWindow", "RxPower"))
        self.label_temp_17.setText(_translate("MainWindow", "dBm"))
        self.label_temp_11.setText(_translate("MainWindow", "ma"))
        self.label_temp_9.setText(_translate("MainWindow", "CH1"))
        self.label_temp_23.setText(_translate("MainWindow", "TxPower"))
        self.label_temp_8.setText(_translate("MainWindow", "CH3"))
        self.label_temp_16.setText(_translate("MainWindow", "dBm"))
        self.label_temp_20.setText(_translate("MainWindow", "dBm"))
        self.label_temp_18.setText(_translate("MainWindow", "dBm"))
        self.label_temp_14.setText(_translate("MainWindow", "dBm"))
        self.label_temp_12.setText(_translate("MainWindow", "ma"))
        self.label_temp_19.setText(_translate("MainWindow", "dBm"))
        self.label_temp_13.setText(_translate("MainWindow", "ma"))
        self.label_temp_5.setText(_translate("MainWindow", "CH2"))
        self.label_temp_6.setText(_translate("MainWindow", "CH4"))
        self.label_temp_21.setText(_translate("MainWindow", "dBm"))
        self.label_temp_25.setText(_translate("MainWindow", "."))
        self.label_temp_26.setText(_translate("MainWindow", "."))
        self.label_temp_47.setText(_translate("MainWindow", "TLos"))
        self.label_temp_33.setText(_translate("MainWindow", "CH1"))
        self.label_temp_48.setText(_translate("MainWindow", "TFau"))
        self.label_temp_49.setText(_translate("MainWindow", "TLol"))
        self.label_temp_50.setText(_translate("MainWindow", "PLos"))
        self.label_temp_51.setText(_translate("MainWindow", "RLol"))
        self.label_temp_53.setText(_translate("MainWindow", "BiHa"))
        self.label_temp_52.setText(_translate("MainWindow", "BiHw"))
        self.label_temp_54.setText(_translate("MainWindow", "BiLw"))
        self.label_temp_55.setText(_translate("MainWindow", "BiLa"))
        self.label_temp_37.setText(_translate("MainWindow", "CH2"))
        self.label_temp_38.setText(_translate("MainWindow", "CH3"))
        self.label_temp_40.setText(_translate("MainWindow", "CH4"))
        self.label_temp_36.setText(_translate("MainWindow", "CH4"))
        self.label_temp_60.setText(_translate("MainWindow", "RxHa"))
        self.label_temp_35.setText(_translate("MainWindow", "CH2"))
        self.label_temp_34.setText(_translate("MainWindow", "CH1"))
        self.label_temp_39.setText(_translate("MainWindow", "CH3"))
        self.label_temp_64.setText(_translate("MainWindow", "TxHw"))
        self.label_temp_62.setText(_translate("MainWindow", "TxLa"))
        self.label_temp_61.setText(_translate("MainWindow", "TxLw"))
        self.label_temp_63.setText(_translate("MainWindow", "RxHw"))
        self.label_temp_67.setText(_translate("MainWindow", "RxLw"))
        self.label_temp_65.setText(_translate("MainWindow", "RxLa"))
        self.label_temp_66.setText(_translate("MainWindow", "TxHa"))
        self.label_temp_43.setText(_translate("MainWindow", "Temp"))
        self.label_temp_71.setText(_translate("MainWindow", "Lw"))
        self.label_temp_42.setText(_translate("MainWindow", "VCC"))
        self.label_temp_69.setText(_translate("MainWindow", "Hw"))
        self.label_temp_75.setText(_translate("MainWindow", "Ha"))
        self.label_temp_70.setText(_translate("MainWindow", "La"))
        self.label_temp_44.setText(_translate("MainWindow", "Initialization complete"))
        self.label_2.setText(_translate("MainWindow", "未连接"))
        self.label_3.setText(_translate("MainWindow", "连接正常"))
        self.label_4.setText(_translate("MainWindow", "连接异常"))
        self.label_temp_58.setText(_translate("MainWindow", "CH4"))
        self.label_temp_56.setText(_translate("MainWindow", "CHA11"))
        self.label_temp_45.setText(_translate("MainWindow", "Tx_Disable"))
        self.label_temp_41.setText(_translate("MainWindow", "CH1"))
        self.label_temp_46.setText(_translate("MainWindow", "CH2"))
        self.label_temp_57.setText(_translate("MainWindow", "CH3"))
        self.label_5.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "DDM"))
        self.label_temp_7.setText(_translate("MainWindow", "-40℃"))
        self.label_temp_27.setText(_translate("MainWindow", "-10℃"))
        self.label_temp_31.setText(_translate("MainWindow", "  0℃"))
        self.label_temp_30.setText(_translate("MainWindow", " 40℃"))
        self.label_temp_29.setText(_translate("MainWindow", " 70℃"))
        self.label_temp_28.setText(_translate("MainWindow", " 85℃"))
        self.pushButton_light_read.setText(_translate("MainWindow", "读"))
        self.pushButton_light_write.setText(_translate("MainWindow", "写"))
        self.label_6.setText(_translate("MainWindow", "调整消光比"))
        self.label_7.setText(_translate("MainWindow", "温度校准"))
        self.label_temp_59.setText(_translate("MainWindow", "℃"))
        self.label_temp_32.setText(_translate("MainWindow", "℃"))
        self.label_temp_68.setText(_translate("MainWindow", "DDM温度："))
        self.label_temp_73.setText(_translate("MainWindow", "目标温度："))
        self.pushButton_ddm_write.setText(_translate("MainWindow", "写"))
        self.label_8.setText(_translate("MainWindow", "100G补充操作"))
        self.pushButton_close_burn.setText(_translate("MainWindow", "关闭BurnIn"))
        self.label_temp_72.setText(_translate("MainWindow", "SN:"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出测试"))



# if __name__ == '__main__':
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     window = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(window)
#     window.show()
#     sys.exit(app.exec_())